### ISSUE TITLE
Splitting the API ref into several Markdown pages

### ISSUE THREAD

**Issue by feloy** [kubernetes-sigs/reference-docs#173]
As part of my Google Season of Docs project (https://developers.google.com/season-of-docs/docs/participants/project-cncf-feloy), I would like to work on the `gen-apidocs` tool, so it can output several Markdown files, in a format supported by Hugo/Docsy for k/website.

I propose to add a second implementation of the `DocWriter` interface, implementing the Markdown for Docsy output.

**Comment by tengqm** [comment]
Looking forward to your code.

**Comment by tengqm** [comment]
A long time ago, we had something similar in generating mardkown files then convert the markdown files into HTML using downstream renders/engines. That markdown writer was abandoned because we don't think another conversion is necessary.

**Comment by feloy** [comment]
> A long time ago, we had something similar in generating mardkown files then convert the markdown files into HTML using downstream renders/engines. That markdown writer was abandoned because we don't think another conversion is necessary.

I can see an advantage of creating Markdown at this step, so that this Markdown can be processed by Hugo/Docsy at the same time as the k/website, so the final HTML is homogeneous with the whole k/website.

**Comment by kbhawkey** [comment]
Do you plan to continue to filter the Open API spec into spec snippets and use these files to generate the individual pages (as an intermediate publishing step)?
I'm not sure it makes sense to create Markdown instead of HTML.
What do you think about adding a Hugo submodule to this repo (#155)?

**Comment by feloy** [comment]
I don't think it will be necessary to pre-process the openAPI spec, it seems possible to generate individual pages directly from the gen-apidocs program.

I'm not very aware of the possibilities of Hugo: would you prefer to still generate HTML with gen-apidocs, containing only the spec content (no header, no footer, no sidebar, etc), then integrate these HTML snippets into pages (with some shortcode or something else?)

My idea was to create Markdown pages, one per resource, including metadatas, so these Markdown pages can be included in k/website (with the help of a submodule), and the pages would be finally rendered by Hugo to create HTML.

**Comment by kbhawkey** [comment]
> I don't think it will be necessary to pre-process the openAPI spec, it seems possible to generate individual pages directly from the gen-apidocs program.
> 
> I'm not very aware of the possibilities of Hugo: would you prefer to still generate HTML with gen-apidocs, containing only the spec content (no header, no footer, no sidebar, etc), then integrate these HTML snippets into pages (with some shortcode or something else?)
> 
> My idea was to create Markdown pages, one per resource, including metadatas, so these Markdown pages can be included in k/website (with the help of a submodule), and the pages would be finally rendered by Hugo to create HTML.

-- If you write out the front matter (and declare the layout type) and place this page in the docs file system, Hugo should build as expected. Or could write a page with the front matter and include an HTML snippet.

-- What about using a [modified] swagger-ui stylesheet and try to replicate the swagger-ui page
components + presentation?  Each page is somewhat contained and displays the nested objects within the root object (linked up)
versus displaying referenced objects after the root object.

**Comment by tengqm** [comment]
> -- What about using a [modified] swagger-ui stylesheet and try to replicate the swagger-ui page components + presentation?

My understanding is that @feloy prefers the same look and feel of the rest of the website. Given that we have about 90 resources in 1.19, that means we will need about 90 markdowns, divided into different groups. 

**Note** When I say 90, I am treating Deployment for creation and Deployment for update two different things because these two have a little bit difference among their schemas. When creating a Deployment, `metadata.name` is required field, but it is optional for an update operation, for example. If you don't want to do this level of differentiation, you still get about 60 resources.

![image](https://user-images.githubusercontent.com/5094756/95694903-fe71cb00-0c66-11eb-8ced-694786a5934d.png)

My points are as follows:

- If we decide to go down this direction, we will still need some kind of navigation scheme (i.e. subdirectories) and asset (i.e. the _index.md files). If we can improve the navigation bar on the left for our current page, this can be easily solved.
- You may have noticed that there are about 800 definitions in 1.19. If we want to generate markdowns only for resources, we will need to make each of those pages self-contained. For example, you will need to replicate "`meta.v1.ObjectMeta`" to many of these pages.
- Converging to the same look & feel is nice to have. I'm a little bit confused about the actual gain we will get.
- Consolidating all definitions referenced by one resource into a single self-contained schema is attractive. If crafted carefully, we will save user's time on traversing the definition hierarchy.

**Comment by sftim** [comment]
How about producing [headless bundles](https://gohugo.io/content-management/page-bundles/#headless-bundle) for each API element (versioned resource)?

How this could work:
1. The reference docs generator fetches the API definitions as OpenAPI
2. The reference docs generator writes a headless bundle for each resource (_example follows_).
    The path to each (headless) leaf bundle is based on the URI path in the API.
3. A custom Hugo layout references all the API bundles for an API group and renders it to HTML.
4. Additionally, concept pages can include the same headless bundle using a new [shortcode](https://gohugo.io/content-management/shortcodes/).
   There are several rendering options; for example
   - a page per API group
   - use data from the extras file (see suggestion below) to identify how to group these data
5. Things that are similar to HTTP-accessible APIs can also have their own headless bundle and share common rendering code. See https://github.com/kubernetes/website/issues/23889

Here's an example of how the headless bundle could look for Lease, as a file named
(eg) `/content/en/docs/apis/coordination.k8s.io/v1/lease.md`
```yaml
---
content_type: api-reference
title: Lease
sitemap_exclude: true
headless: true
api:
  - namespaced: true # used to adjust the API path automatically
    fields:
    - name: apiVersion
      type: string
      useDefaultText: true
    - name: kind
      type: string
      useDefaultText: true
    - name: spec 
      # The "text" field contains generated Markdown.
      text: >
        Specification of the Lease. More info:
        https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
      fields:
        - name: acquireTime
          type: MicroTime
          typeApiGroup: meta/v1
          text: >
            `acquireTime` is a time when the current lease was acquired.
        - name: renewTime
          type: MicroTime
          typeApiGroup: meta/v1
          text: >
            `renewTime` is a time when the current holder of a lease has last updated the lease.
        - name: leaseDurationSeconds
          type: integer
          text: >
            `leaseDurationSeconds` is a duration that candidates for a lease need to wait to
            force acquire  it. This is measure against time of last observed `RenewTime`.
        - name: leaseTransitions
          type: integer
          text: >
            `leaseTransitions` is the number of transitions of a lease between holders.
        - name: holderIdentity
          type: string
          text: >
            `holderIdentity` contains the identity of the holder of a current lease.
        …
    operations:
       - name: Read
         operationRepresentsWrite: false
         HTTPVerb: GET
         # no backticks for pathTemplateMarkDown
         # the (imaginary) API reference layout automatically wraps this in a <tt> element
         pathTemplateMarkDown: "/apis/coordination.k8s.io/v1/namespaces/_{namespace}_/leases/_{name}_"
         queryParameters:
           - name: export
             deprecated: true
             text: >
               …
           - name: pretty
             deprecated: false
             text: >
          …    
---
```
and a related file named eg `/content/en/docs/api-extras/coordination.k8s.io/v1/lease.md`:
```markdown
---
content_type: api-reference-extras
title: Lease
sitemap_exclude: true
headless: true
version_support:
  # rough sketch!
  - beta:
      start: v1.14
      # could have end: v1.xx when this is deprecated, not sure the beta Lease API _is_ deprecated yet
  - stable:
      start: v1.17
extraData:
   feature_state: stable
---

A _Lease_ allows a Kubernetes principal to request and then hold a time-limited lock or reservation
against a related object.

## Uses

Each Node has an associated Lease object in the `kube-node-lease`
{{< glossary_tooltip term_id="namespace" text="namespace">}}.
Lease is a lightweight resource, which improves the performance
of the node heartbeats as the cluster scales.

&hellip;

## {{% heading "whatsnext" %}}
<!-- more stuff -->
```
_note_ that if the extras file isn't there, the API documentation still renders. In this sketch, the optional extras file provides a way for humans to add details that aren't generatable and provide relevant outbound hyperlinks. In the future, some of the things I've shown being in the extras file could be moved into [k/kubernetes](https://github.com/kubernetes/kubernetes) and then become part of the generated file instead.

and here's an example of using the shortcode:
```markdown
For more information on the resources you can use to expose your application, see:
- {{% api-reference target="v1/Service" length="short" %}}
- {{% api-reference target="v1/Ingress" api_group="networking.k8s.io" length="short" %}}
```

Another option is to use [data templates](https://gohugo.io/templates/data-templates/). I picked headless bundles because data templates aren't easy to localize.
